// <auto-generated />
using System;
using System.Collections.Generic;
using DemoGraphQL.Server.Entities;
using DemoGraphQL.Server.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoGraphQL.Server.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220126090907_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("DemoGraphQL.Server.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("numberOfKeys")
                    .IsRequired()
                    .HasColumnType("INTEGER");

                    b.Property<string>("role")
                    .IsRequired()
                    .HasColumnType("TEXT");

                    b.Property<string>("inventory")
                    .IsRequired()
                    .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10f8dac5-2e64-48a2-a3b0-ada65c4ed3d1"),
                            Name = "Armure",
                            numberOfKeys = 0,
                            role = UserRoles.Admin,
                            inventory = new List<Item>()
                        },
                        new
                        {
                            Id = new Guid("34686dae-a622-4464-921c-b7f682b61ecc"),
                            Name = "Rayhan",
                            numberOfKeys = 0,
                            role = UserRoles.User,
                            inventory = new List<Item>()
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
